import { RawQrDecoder } from './decoder';

export class CameraController {
  private stream?: MediaStream; private timer?: number; private inFlight = false; private generation = 0; private readonly decoder = new RawQrDecoder();
  constructor(private readonly video: HTMLVideoElement, private readonly canvas: HTMLCanvasElement, private readonly onBytes: (bytes: Uint8Array) => void, private readonly onError: (message: string) => void) {}
  async start(): Promise<void> { this.stop(); const generation = ++this.generation; try { this.stream = await navigator.mediaDevices.getUserMedia({ audio: false, video: { facingMode: { ideal: 'environment' }, width: { ideal: 1280 }, height: { ideal: 720 } } }); if (generation !== this.generation) { this.stream.getTracks().forEach((track) => track.stop()); return; } this.video.srcObject = this.stream; await this.video.play(); this.schedule(generation); } catch (error) { const name = error instanceof DOMException ? error.name : 'UnknownError'; this.onError(name === 'NotAllowedError' ? 'CAMERA_PERMISSION_DENIED' : name === 'NotFoundError' ? 'CAMERA_UNAVAILABLE' : 'CAMERA_STREAM_FAILED'); throw error; } }
  stop(): void { this.generation++; if (this.timer) window.clearTimeout(this.timer); this.timer = undefined; this.stream?.getTracks().forEach((track) => track.stop()); this.stream = undefined; this.video.pause(); this.video.srcObject = null; this.inFlight = false; }
  dispose(): void { this.stop(); this.decoder.dispose(); }
  private schedule(generation: number): void { this.timer = window.setTimeout(async () => { if (generation !== this.generation || !this.stream) return; if (this.inFlight || this.video.readyState < HTMLMediaElement.HAVE_CURRENT_DATA) return this.schedule(generation); this.inFlight = true; try { const width = this.video.videoWidth; const height = this.video.videoHeight; if (width && height) { this.canvas.width = width; this.canvas.height = height; const context = this.canvas.getContext('2d', { willReadFrequently: true }); if (context) { context.drawImage(this.video, 0, 0, width, height); const bytes = await this.decoder.decode(context.getImageData(0, 0, width, height)); if (bytes && generation === this.generation) this.onBytes(bytes); } } } finally { this.inFlight = false; if (generation === this.generation && this.stream) this.schedule(generation); } }, 90); }
}
