/**
 * Phase 00 — Baseline Audit Harness
 *
 * Drives the real shipping modules (`session-manager` constants, `container`,
 * `fountain-encoder`, `protocol`, and the browser-safe `ReceiverSession`) over a
 * size sweep and an extension matrix, recording per-stage timings, byte counts,
 * and memory growth.
 *
 * It exists to answer two questions with runtime evidence rather than source
 * reading:
 *   1. exactly where DEQR stops accepting large files, and why;
 *   2. whether an identical byte sequence transfers differently when only its
 *      filename extension changes.
 *
 * Payload safety: no transferred bytes, no absolute source paths, and no
 * cryptographic key material are written to the evidence file. Corpora are
 * deterministic synthetic bytes generated by this script.
 *
 *   node node_modules/vite-node/vite-node.mjs scripts/bench/phase00-baseline.ts -- --help
 */

import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { gzipSync } from 'node:zlib';
import * as fs from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { performance } from 'node:perf_hooks';
import { arch, platform, release, totalmem } from 'node:os';
import { relative, resolve } from 'node:path';

import { computeSha256 } from '../../src/core/hash';
import { PROTOCOL_VERSION, serializeContainer, MAX_FILE_SIZE } from '../../src/core/container';
import { FountainEncoder } from '../../src/core/fountain-encoder';
import { serializeFrame } from '../../src/core/protocol';
import { isBlockedExtension } from '../../src/core/filename-sanitizer';
import {
  V1_FOUNTAIN_BLOCK_SIZE_BYTES,
  V1_MAX_BLOCK_COUNT,
  V1_MAX_SERIALIZED_CONTAINER_BYTES,
} from '../../src/main/session-manager';
import { ReceiverSession } from '../../mobile-web/src/protocol';

const MIB = 1024 * 1024;

/** The shipping sender cadence. `src/main/ipc-handlers.ts` emits one frame per tick. */
const SHIPPING_TRANSFER_FPS = 10;

/** Frames sampled when a scenario is too large to encode end to end. */
const ENCODE_SAMPLE_FRAMES = 4_096;

const DEFAULT_SIZES_MIB = [1, 16, 32, 48, 64] as const;
const DEFAULT_EXTENSIONS = ['.txt', '.pdf', '.zip', '.xlsx', '.bin'] as const;
const SESSION_ID = 0x5eed_1234;
const MIME_TYPE = 'application/octet-stream';

/**
 * Two naming schemes for the same bytes.
 *
 * `natural` uses one base name, so `.xlsx` is one byte longer than the rest.
 * `equalLength` holds the filename to twelve bytes for every extension, which
 * removes that single confound: any remaining difference would have to come
 * from the extension itself.
 */
const EXTENSION_NAME_SETS: Record<'natural' | 'equalLength', Record<string, string>> = {
  natural: {
    '.txt': 'identical-bytes.txt',
    '.pdf': 'identical-bytes.pdf',
    '.zip': 'identical-bytes.zip',
    '.xlsx': 'identical-bytes.xlsx',
    '.bin': 'identical-bytes.bin',
  },
  equalLength: {
    '.txt': 'sample01.txt',
    '.pdf': 'sample01.pdf',
    '.zip': 'sample01.zip',
    '.xlsx': 'sample1.xlsx',
    '.bin': 'sample01.bin',
  },
};

type Corpus = 'text' | 'random';
type Mode = 'all' | 'capacity' | 'extension' | 'boundary';

interface Options {
  mode: Mode;
  sizesMib: number[];
  samples: number;
  decodeMaxMib: number;
  extensionSizeMib: number;
  output: string;
  label: string;
}

interface MemorySample {
  rssBytes: number;
  heapUsedBytes: number;
  externalBytes: number;
  arrayBuffersBytes: number;
}

function usage(): string {
  return [
    'Phase 00 baseline harness',
    '',
    '  --mode all|capacity|extension|boundary   (default all)',
    '  --sizes 1,16,32,48,64           MiB sweep for the capacity mode',
    '  --samples 3                     repeats of the extension matrix',
    '  --decode-max-mib 32             largest container to decode end to end',
    '  --extension-size-mib 4          payload size used for the extension matrix',
    '  --label baseline                evidence label',
    '  --output <path under .local-run/bench/>',
  ].join('\n');
}

function positiveInteger(value: string | undefined, name: string, fallback: number): number {
  if (value === undefined) return fallback;
  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed < 1 || parsed > 4_096) {
    throw new Error(`${name} must be an integer between 1 and 4096.`);
  }
  return parsed;
}

function parseOptions(argumentsList: string[]): Options {
  const values = new Map<string, string>();
  for (let index = 0; index < argumentsList.length; index += 1) {
    const argument = argumentsList[index];
    if (argument === '--help' || argument === '-h') {
      console.log(usage());
      process.exit(0);
    }
    if (!argument.startsWith('--')) throw new Error(`Unexpected argument: ${argument}`);
    const value = argumentsList[index + 1];
    if (value === undefined || value.startsWith('--')) throw new Error(`Missing value for ${argument}`);
    values.set(argument, value);
    index += 1;
  }

  const label = values.get('--label') ?? 'baseline';
  if (!/^[a-z0-9][a-z0-9._-]*$/i.test(label)) {
    throw new Error('--label may contain only letters, numbers, dots, underscores, and hyphens.');
  }

  const mode = (values.get('--mode') ?? 'all') as Mode;
  if (!['all', 'capacity', 'extension', 'boundary'].includes(mode)) {
    throw new Error('--mode must be all, capacity, extension, or boundary.');
  }

  const sizesMib = (values.get('--sizes') ?? DEFAULT_SIZES_MIB.join(','))
    .split(',')
    .map((entry) => Number(entry.trim()))
    .filter((entry) => entry > 0);
  if (!sizesMib.length || sizesMib.some((entry) => !Number.isInteger(entry) || entry > 4_096)) {
    throw new Error('--sizes must be a comma-separated list of MiB integers up to 4096.');
  }

  return {
    mode,
    sizesMib,
    samples: positiveInteger(values.get('--samples'), '--samples', 3),
    decodeMaxMib: positiveInteger(values.get('--decode-max-mib'), '--decode-max-mib', 32),
    extensionSizeMib: positiveInteger(values.get('--extension-size-mib'), '--extension-size-mib', 4),
    output: values.get('--output') ?? `.local-run/bench/phase00-baseline-${label}.json`,
    label,
  };
}

function resolveOutputPath(rawOutput: string): string {
  const allowedRoot = resolve(process.cwd(), '.local-run', 'bench');
  const output = resolve(process.cwd(), rawOutput);
  const outputRelative = relative(allowedRoot, output);
  if (outputRelative.startsWith('..') || outputRelative === '' || outputRelative.includes(':')) {
    throw new Error('Benchmark output must be a file below .local-run/bench/.');
  }
  return output;
}

/* ------------------------------------------------------------------ corpora */

/** Deterministic high-entropy bytes. gzip cannot shrink these. */
function randomBytes(length: number, seed: number): Buffer {
  const bytes = Buffer.allocUnsafe(length);
  let state = seed >>> 0;
  for (let index = 0; index < length; index += 1) {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    bytes[index] = state >>> 24;
  }
  return bytes;
}

const WORDS = [
  'transfer', 'optical', 'fountain', 'segment', 'container', 'protocol', 'receiver',
  'sender', 'integrity', 'checksum', 'stream', 'bounded', 'window', 'symbol', 'repair',
  'systematic', 'offline', 'verified', 'throughput', 'baseline',
];

/** Deterministic text-like bytes with real redundancy, so gzip has something to find. */
function textBytes(length: number, seed: number): Buffer {
  const bytes = Buffer.alloc(length, 0x20);
  let state = seed >>> 0;
  let offset = 0;
  let column = 0;
  while (offset < length) {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    const word = WORDS[(state >>> 16) % WORDS.length];
    const chunk = column > 68 ? `${word}\n` : `${word} `;
    if (offset + chunk.length > length) break;
    column = column > 68 ? 0 : column + chunk.length;
    offset += bytes.write(chunk, offset, 'latin1');
  }
  return bytes;
}

function buildCorpus(corpus: Corpus, length: number, seed: number): Buffer {
  return corpus === 'text' ? textBytes(length, seed) : randomBytes(length, seed);
}

/* ---------------------------------------------------------------- utilities */

function snapshot(): MemorySample {
  const usage = process.memoryUsage();
  return {
    rssBytes: usage.rss,
    heapUsedBytes: usage.heapUsed,
    externalBytes: usage.external,
    arrayBuffersBytes: usage.arrayBuffers,
  };
}

function peak(samples: MemorySample[]): MemorySample {
  return {
    rssBytes: Math.max(...samples.map((entry) => entry.rssBytes)),
    heapUsedBytes: Math.max(...samples.map((entry) => entry.heapUsedBytes)),
    externalBytes: Math.max(...samples.map((entry) => entry.externalBytes)),
    arrayBuffersBytes: Math.max(...samples.map((entry) => entry.arrayBuffersBytes)),
  };
}

function timed<T>(operation: () => T): { value: T; ms: number } {
  const start = performance.now();
  const value = operation();
  return { value, ms: performance.now() - start };
}

async function timedAsync<T>(operation: () => Promise<T>): Promise<{ value: T; ms: number }> {
  const start = performance.now();
  const value = await operation();
  return { value, ms: performance.now() - start };
}

function bytesPerSecond(bytes: number, ms: number): number {
  return ms > 0 ? bytes / (ms / 1_000) : 0;
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

/**
 * Compressibility measured the way Phase 08 will have to measure it: from
 * bounded samples of the actual bytes, never from the extension.
 */
function sampleCompressibility(source: Buffer): {
  compressionInputBytes: number;
  compressionOutputBytes: number;
  compressionMs: number;
  sampledRatio: number;
} {
  const sampleSize = Math.min(source.length, 1 * MIB);
  const offsets = [
    0,
    Math.max(0, Math.floor(source.length / 2) - sampleSize),
    Math.max(0, source.length - sampleSize),
  ];
  const unique = [...new Set(offsets)];
  let input = 0;
  let output = 0;
  const start = performance.now();
  for (const offset of unique) {
    const slice = source.subarray(offset, offset + sampleSize);
    input += slice.length;
    output += gzipSync(slice, { level: 6 }).length;
  }
  const compressionMs = performance.now() - start;
  return {
    compressionInputBytes: input,
    compressionOutputBytes: output,
    compressionMs,
    sampledRatio: input > 0 ? output / input : 1,
  };
}

/* ------------------------------------------------------------ capacity mode */

interface CapacityScenario {
  corpus: Corpus;
  sizeMib: number;
  sizeBytes: number;
  filename: string;
  fileReadMs: number;
  fileReadBytesPerSec: number;
  hashMs: number;
  hashBytesPerSec: number;
  compressionInputBytes: number;
  compressionOutputBytes: number;
  compressionMs: number;
  sampledCompressionRatio: number;
  containerSerializeMs: number;
  containerBytes: number;
  containerOverheadBytes: number;
  selectionGate: 'accepted' | 'rejected-raw-size' | 'rejected-serialized-size';
  selectionGateThresholdBytes: number;
  encoderConstructed: boolean;
  encoderError: string | null;
  encoderInitMs: number;
  blockCount: number | null;
  frameBytes: number | null;
  encodeSampleFrames: number;
  encodeSampleMs: number;
  fountainEncodeSymbolsPerSec: number;
  opticalPayloadBytesPerSec: number;
  projectedSystematicPassSeconds: number | null;
  decodeAttempted: boolean;
  decodeSkippedReason: string | null;
  uniqueFramesAccepted: number;
  duplicatesDropped: number;
  framesRejected: number;
  pwaReceiveMs: number;
  fountainDecodeSymbolsPerSec: number;
  verifyMs: number;
  verifyBytesPerSec: number;
  verifyOutcome: string;
  endToEndCpuMs: number;
  memoryBefore: MemorySample;
  memoryPeak: MemorySample;
  peakRssOverSizeRatio: number;
}

async function runCapacityScenario(
  corpus: Corpus,
  sizeMib: number,
  corpusDir: string,
  decodeMaxBytes: number,
): Promise<CapacityScenario> {
  const sizeBytes = sizeMib * MIB;
  const filename = `phase00-${corpus}-${sizeMib}mib.bin`;
  const filePath = resolve(corpusDir, filename);

  if (!fs.existsSync(filePath) || fs.statSync(filePath).size !== sizeBytes) {
    const generated = buildCorpus(corpus, sizeBytes, (SESSION_ID ^ sizeBytes ^ (corpus === 'text' ? 1 : 2)) >>> 0);
    fs.writeFileSync(filePath, generated);
    generated.fill(0);
  }

  const memoryBefore = snapshot();
  const memorySamples: MemorySample[] = [memoryBefore];
  const startedAt = performance.now();

  // Stage 1 — whole-file read. This is exactly what `SessionManager.selectFile` does.
  const read = timed(() => fs.readFileSync(filePath));
  const source = read.value;
  memorySamples.push(snapshot());

  // Stage 2 — SHA-256 over the whole buffer.
  const hash = timed(() => computeSha256(source));
  memorySamples.push(snapshot());

  // Stage 3 — sampled compressibility. The shipping sender never calls this.
  const compressibility = sampleCompressibility(source);

  // Stage 4 — container serialization: a second whole-file allocation and copy.
  const container = timed(() => serializeContainer({
    metadata: {
      protocolVersion: PROTOCOL_VERSION,
      filename,
      mimeType: MIME_TYPE,
      originalSize: source.length,
      compressed: false,
      encrypted: false,
      timestamp: 0,
      sha256: hash.value,
    },
    payload: source,
  }));
  const containerBytes = container.value;
  memorySamples.push(snapshot());

  // Stage 5 — the two shipping selection gates, in the order the sender applies them.
  const selectionGate: CapacityScenario['selectionGate'] =
    sizeBytes >= V1_MAX_SERIALIZED_CONTAINER_BYTES
      ? 'rejected-raw-size'
      : containerBytes.length > V1_MAX_SERIALIZED_CONTAINER_BYTES
        ? 'rejected-serialized-size'
        : 'accepted';

  // Stage 6 — encoder construction. Run regardless of the gate, so the
  // underlying protocol failure is observed rather than inferred from it.
  const encoderInit = timed((): { encoder: FountainEncoder | null; error: string | null } => {
    try {
      return {
        encoder: new FountainEncoder(containerBytes, V1_FOUNTAIN_BLOCK_SIZE_BYTES, SESSION_ID),
        error: null,
      };
    } catch (error) {
      return { encoder: null, error: errorMessage(error) };
    }
  });
  memorySamples.push(snapshot());

  const active = encoderInit.value.encoder;
  const encoderError = encoderInit.value.error;
  const blockCount = active ? active.getBlockCount() : null;

  // Stage 7 — frame generation rate over a bounded sample.
  let encodeSampleFrames = 0;
  let encodeSampleMs = 0;
  let frameBytes: number | null = null;
  if (active) {
    const target = Math.min(ENCODE_SAMPLE_FRAMES, blockCount ?? 0);
    const start = performance.now();
    for (let index = 0; index < target; index += 1) {
      frameBytes = serializeFrame(active.nextFrame()).length;
      encodeSampleFrames += 1;
    }
    encodeSampleMs = performance.now() - start;
  }
  memorySamples.push(snapshot());

  const projectedSystematicPassSeconds = blockCount === null ? null : blockCount / SHIPPING_TRANSFER_FPS;

  // Stage 8 — receiver. Bounded by --decode-max-mib because the shipping
  // receiver holds the entire transfer in memory, and this harness must not be
  // what decides how much of that a workstation can survive.
  let decodeAttempted = false;
  let decodeSkippedReason: string | null = null;
  let uniqueFramesAccepted = 0;
  let duplicatesDropped = 0;
  let framesRejected = 0;
  let pwaReceiveMs = 0;
  let verifyMs = 0;
  let verifyOutcome = 'not-attempted';

  if (!active) {
    decodeSkippedReason = 'sender never produced a frame stream';
  } else if (containerBytes.length > decodeMaxBytes) {
    decodeSkippedReason = `container ${containerBytes.length} bytes exceeds --decode-max-mib`;
  } else {
    decodeAttempted = true;
    // The sample above already consumed sequence numbers, so restart the stream
    // to give the receiver a systematic-first pass.
    const streamEncoder = new FountainEncoder(containerBytes, V1_FOUNTAIN_BLOCK_SIZE_BYTES, SESSION_ID);
    const receiver = new ReceiverSession();
    let state = receiver.snapshot();
    const maxFrames = (blockCount ?? 0) * 2 + 128;
    let generated = 0;
    const start = performance.now();
    while (state.state !== 'VERIFYING' && generated < maxFrames) {
      const raw = new Uint8Array(serializeFrame(streamEncoder.nextFrame()));
      generated += 1;
      const previousDuplicates = state.duplicates;
      state = receiver.receive(raw);
      if (state.state === 'FAILED') {
        framesRejected += 1;
        break;
      }
      if (state.duplicates > previousDuplicates) duplicatesDropped += 1;
      else uniqueFramesAccepted += 1;
    }
    pwaReceiveMs = performance.now() - start;
    memorySamples.push(snapshot());

    const verification = await timedAsync(() => receiver.verify());
    verifyMs = verification.ms;
    verifyOutcome = verification.value.state === 'COMPLETE'
      ? 'COMPLETE'
      : `${verification.value.state}:${verification.value.error?.code ?? 'unknown'}`;
    memorySamples.push(snapshot());
    receiver.reset();
  }

  const endToEndCpuMs = performance.now() - startedAt;
  const memoryPeak = peak(memorySamples);
  source.fill(0);
  containerBytes.fill(0);

  return {
    corpus,
    sizeMib,
    sizeBytes,
    filename,
    fileReadMs: read.ms,
    fileReadBytesPerSec: bytesPerSecond(sizeBytes, read.ms),
    hashMs: hash.ms,
    hashBytesPerSec: bytesPerSecond(sizeBytes, hash.ms),
    compressionInputBytes: compressibility.compressionInputBytes,
    compressionOutputBytes: compressibility.compressionOutputBytes,
    compressionMs: compressibility.compressionMs,
    sampledCompressionRatio: compressibility.sampledRatio,
    containerSerializeMs: container.ms,
    containerBytes: containerBytes.length,
    containerOverheadBytes: containerBytes.length - sizeBytes,
    selectionGate,
    selectionGateThresholdBytes: V1_MAX_SERIALIZED_CONTAINER_BYTES,
    encoderConstructed: active !== null,
    encoderError,
    encoderInitMs: encoderInit.ms,
    blockCount,
    frameBytes,
    encodeSampleFrames,
    encodeSampleMs,
    fountainEncodeSymbolsPerSec: encodeSampleMs > 0 ? encodeSampleFrames / (encodeSampleMs / 1_000) : 0,
    opticalPayloadBytesPerSec: SHIPPING_TRANSFER_FPS * V1_FOUNTAIN_BLOCK_SIZE_BYTES,
    projectedSystematicPassSeconds,
    decodeAttempted,
    decodeSkippedReason,
    uniqueFramesAccepted,
    duplicatesDropped,
    framesRejected,
    pwaReceiveMs,
    fountainDecodeSymbolsPerSec: pwaReceiveMs > 0 ? uniqueFramesAccepted / (pwaReceiveMs / 1_000) : 0,
    verifyMs,
    verifyBytesPerSec: bytesPerSecond(sizeBytes, verifyMs),
    verifyOutcome,
    endToEndCpuMs,
    memoryBefore,
    memoryPeak,
    peakRssOverSizeRatio: memoryPeak.rssBytes / sizeBytes,
  };
}

/* ----------------------------------------------------------- extension mode */

interface ExtensionSample {
  extension: string;
  filename: string;
  filenameBytes: number;
  blockedBySender: boolean;
  containerBytes: number;
  blockCount: number;
  frameBytes: number | null;
  /**
   * SHA-256 of the serialized container with the variable-length filename field
   * removed. Identical values across extensions prove that nothing downstream
   * of the filename can differ.
   */
  containerDigestExcludingFilename: string;
  frameStreamDigest: string;
  framesGenerated: number;
  hashMs: number;
  containerSerializeMs: number;
  encodeMs: number;
  receiveMs: number;
  verifyMs: number;
  endToEndMs: number;
  verifyOutcome: string;
}

function containerDigestExcludingFilename(container: Buffer, filenameBytes: number): string {
  // Layout: magic(4) version(2) filenameLength(2) filename(n) ...
  const head = container.subarray(0, 8);
  const tail = container.subarray(8 + filenameBytes);
  return createHash('sha256').update(head).update(tail).digest('hex');
}

async function runExtensionSample(source: Buffer, extension: string, filename: string): Promise<ExtensionSample> {
  const filenameBytes = Buffer.byteLength(filename, 'utf-8');
  const blockedBySender = isBlockedExtension(filename);
  const startedAt = performance.now();

  const hash = timed(() => computeSha256(source));
  const container = timed(() => serializeContainer({
    metadata: {
      protocolVersion: PROTOCOL_VERSION,
      filename,
      mimeType: MIME_TYPE,
      originalSize: source.length,
      compressed: false,
      encrypted: false,
      timestamp: 0,
      sha256: hash.value,
    },
    payload: source,
  }));

  const digest = containerDigestExcludingFilename(container.value, filenameBytes);

  const encoderInit = timed(() => new FountainEncoder(container.value, V1_FOUNTAIN_BLOCK_SIZE_BYTES, SESSION_ID));
  const encoder = encoderInit.value;
  const blockCount = encoder.getBlockCount();

  const receiver = new ReceiverSession();
  const streamHash = createHash('sha256');
  let state = receiver.snapshot();
  let frameBytes: number | null = null;
  let encodeMs = 0;
  let receiveMs = 0;
  const maxFrames = blockCount * 2 + 128;
  let generated = 0;

  while (state.state !== 'VERIFYING' && generated < maxFrames) {
    const encodeStart = performance.now();
    const raw = serializeFrame(encoder.nextFrame());
    encodeMs += performance.now() - encodeStart;
    streamHash.update(raw);
    frameBytes = raw.length;
    generated += 1;

    const receiveStart = performance.now();
    state = receiver.receive(new Uint8Array(raw));
    receiveMs += performance.now() - receiveStart;
    if (state.state === 'FAILED') break;
  }

  const verification = await timedAsync(() => receiver.verify());
  const verifyOutcome = verification.value.state === 'COMPLETE'
    ? 'COMPLETE'
    : `${verification.value.state}:${verification.value.error?.code ?? 'unknown'}`;
  receiver.reset();

  return {
    extension,
    filename,
    filenameBytes,
    blockedBySender,
    containerBytes: container.value.length,
    blockCount,
    frameBytes,
    containerDigestExcludingFilename: digest,
    frameStreamDigest: streamHash.digest('hex'),
    framesGenerated: generated,
    hashMs: hash.ms,
    containerSerializeMs: container.ms,
    encodeMs: encodeMs + encoderInit.ms,
    receiveMs,
    verifyMs: verification.ms,
    endToEndMs: performance.now() - startedAt,
    verifyOutcome,
  };
}

/* ------------------------------------------------------------ boundary mode */

interface BoundaryProbe {
  filename: string;
  containerHeaderBytes: number;
  v1MaxSerializedContainerBytes: number;
  largestAcceptedSourceBytes: number;
  largestAcceptedSourceMib: number;
  atCeiling: { sourceBytes: number; containerBytes: number; gate: string; blockCount: number | null; encoderError: string | null };
  oneByteOver: { sourceBytes: number; containerBytes: number; gate: string; blockCount: number | null; encoderError: string | null };
  rawSizeGateRejectsAtOrAbove: number;
  nominal32MibRejected: boolean;
}

function containerHeaderBytes(filename: string): number {
  return serializeContainer({
    metadata: {
      protocolVersion: PROTOCOL_VERSION,
      filename,
      mimeType: MIME_TYPE,
      originalSize: 0,
      compressed: false,
      encrypted: false,
      timestamp: 0,
      sha256: Buffer.alloc(32),
    },
    payload: Buffer.alloc(0),
  }).length;
}

function probeSourceSize(filename: string, sourceBytes: number): BoundaryProbe['atCeiling'] {
  const source = Buffer.alloc(sourceBytes, 0xa5);
  try {
    const container = serializeContainer({
      metadata: {
        protocolVersion: PROTOCOL_VERSION,
        filename,
        mimeType: MIME_TYPE,
        originalSize: source.length,
        compressed: false,
        encrypted: false,
        timestamp: 0,
        sha256: computeSha256(source),
      },
      payload: source,
    });

    const gate = sourceBytes >= V1_MAX_SERIALIZED_CONTAINER_BYTES
      ? 'rejected-raw-size'
      : container.length > V1_MAX_SERIALIZED_CONTAINER_BYTES
        ? 'rejected-serialized-size'
        : 'accepted';

    let blockCount: number | null = null;
    let encoderError: string | null = null;
    try {
      blockCount = new FountainEncoder(container, V1_FOUNTAIN_BLOCK_SIZE_BYTES, SESSION_ID).getBlockCount();
    } catch (error) {
      encoderError = errorMessage(error);
    }

    const result = { sourceBytes, containerBytes: container.length, gate, blockCount, encoderError };
    container.fill(0);
    return result;
  } finally {
    source.fill(0);
  }
}

/**
 * Walks the exact v1 capacity boundary so the ceiling is a measured number
 * rather than one read off a constant.
 */
function runBoundaryProbe(): BoundaryProbe {
  const filename = 'boundary-probe.bin';
  const headerBytes = containerHeaderBytes(filename);
  const largestAccepted = V1_MAX_SERIALIZED_CONTAINER_BYTES - headerBytes;
  return {
    filename,
    containerHeaderBytes: headerBytes,
    v1MaxSerializedContainerBytes: V1_MAX_SERIALIZED_CONTAINER_BYTES,
    largestAcceptedSourceBytes: largestAccepted,
    largestAcceptedSourceMib: largestAccepted / MIB,
    atCeiling: probeSourceSize(filename, largestAccepted),
    oneByteOver: probeSourceSize(filename, largestAccepted + 1),
    rawSizeGateRejectsAtOrAbove: V1_MAX_SERIALIZED_CONTAINER_BYTES,
    nominal32MibRejected: 32 * MIB >= V1_MAX_SERIALIZED_CONTAINER_BYTES,
  };
}

/* -------------------------------------------------------------------- entry */

function gitMetadata(): { head: string | null; dirty: boolean | null } {
  try {
    const head = execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
    const dirty = execFileSync('git', ['status', '--porcelain=v1'], { encoding: 'utf8' }).length > 0;
    return { head, dirty };
  } catch {
    return { head: null, dirty: null };
  }
}

function statistics(values: number[]): { min: number; mean: number; max: number; spreadRatio: number } {
  const min = Math.min(...values);
  const max = Math.max(...values);
  const mean = values.reduce((total, value) => total + value, 0) / values.length;
  return { min, mean, max, spreadRatio: min > 0 ? max / min : 0 };
}

async function main(): Promise<void> {
  const options = parseOptions(process.argv.slice(2));
  const output = resolveOutputPath(options.output);
  const corpusDir = resolve(process.cwd(), '.local-run', 'phase00-corpus');
  await mkdir(corpusDir, { recursive: true });
  await mkdir(resolve(output, '..'), { recursive: true });

  let boundary: BoundaryProbe | null = null;
  if (options.mode === 'all' || options.mode === 'boundary') {
    boundary = runBoundaryProbe();
    console.log(
      `BOUNDARY largestAcceptedSource=${boundary.largestAcceptedSourceBytes}`
      + ` (${boundary.largestAcceptedSourceMib.toFixed(6)} MiB)`
      + ` atCeiling=${boundary.atCeiling.gate}/K=${boundary.atCeiling.blockCount}`
      + ` oneByteOver=${boundary.oneByteOver.gate}/K=${boundary.oneByteOver.blockCount ?? 'throw'}`,
    );
  }

  const capacity: CapacityScenario[] = [];
  if (options.mode === 'all' || options.mode === 'capacity') {
    for (const corpus of ['text', 'random'] as Corpus[]) {
      for (const sizeMib of options.sizesMib) {
        if (typeof global.gc === 'function') global.gc();
        const scenario = await runCapacityScenario(corpus, sizeMib, corpusDir, options.decodeMaxMib * MIB);
        capacity.push(scenario);
        console.log(
          `CAPACITY corpus=${corpus} size=${sizeMib}MiB gate=${scenario.selectionGate}`
          + ` blocks=${scenario.blockCount ?? 'n/a'} encoder=${scenario.encoderConstructed ? 'ok' : 'FAILED'}`
          + ` verify=${scenario.verifyOutcome}`
          + ` peakRss=${(scenario.memoryPeak.rssBytes / MIB).toFixed(1)}MiB`,
        );
      }
    }
  }

  type NameScheme = keyof typeof EXTENSION_NAME_SETS;
  const extensionMatrix: Array<{ nameScheme: NameScheme; sample: number; results: ExtensionSample[] }> = [];
  let blockedProbe: ExtensionSample | null = null;
  if (options.mode === 'all' || options.mode === 'extension') {
    // One buffer, five names. Nothing about the bytes changes between runs.
    const source = buildCorpus('random', options.extensionSizeMib * MIB, 0x1234_5678);
    for (const nameScheme of Object.keys(EXTENSION_NAME_SETS) as NameScheme[]) {
      for (let sample = 0; sample < options.samples; sample += 1) {
        if (typeof global.gc === 'function') global.gc();
        const results: ExtensionSample[] = [];
        // Rotate the running order each sample. Whichever extension goes first
        // absorbs that sample's warm-up cost, so rotation stops a fixed order
        // from masquerading as an extension effect.
        const order = DEFAULT_EXTENSIONS.map((_, index) =>
          DEFAULT_EXTENSIONS[(index + sample) % DEFAULT_EXTENSIONS.length]);
        for (const extension of order) {
          const result = await runExtensionSample(source, extension, EXTENSION_NAME_SETS[nameScheme][extension]);
          results.push(result);
          console.log(
            `EXTENSION scheme=${nameScheme} sample=${sample} ext=${extension}`
            + ` container=${result.containerBytes} blocks=${result.blockCount}`
            + ` endToEnd=${result.endToEndMs.toFixed(1)}ms verify=${result.verifyOutcome}`,
          );
        }
        extensionMatrix.push({ nameScheme, sample, results });
      }
    }
    // A blocked extension is a categorical sender reject, not a slow path.
    blockedProbe = await runExtensionSample(source.subarray(0, 64 * 1024), '.exe', 'probe.exe');
    console.log(`EXTENSION blocked-probe ext=.exe blockedBySender=${blockedProbe.blockedBySender}`);
    source.fill(0);
  }

  const summarizeScheme = (nameScheme: NameScheme) => {
    const entries = extensionMatrix.filter((entry) => entry.nameScheme === nameScheme);
    const results = entries.flatMap((entry) => entry.results);
    return {
      distinctContainerDigestsExcludingFilename:
        [...new Set(results.map((result) => result.containerDigestExcludingFilename))].length,
      distinctBlockCounts: [...new Set(results.map((result) => result.blockCount))],
      distinctContainerByteLengths: [...new Set(results.map((result) => result.containerBytes))],
      distinctFilenameByteLengths: [...new Set(results.map((result) => result.filenameBytes))],
      endToEndMsByExtension: Object.fromEntries(DEFAULT_EXTENSIONS.map((extension) => [
        extension,
        statistics(results.filter((result) => result.extension === extension).map((result) => result.endToEndMs)),
      ])),
    };
  };

  const extensionSummary = extensionMatrix.length
    ? {
      natural: summarizeScheme('natural'),
      equalLength: summarizeScheme('equalLength'),
    }
    : null;

  const evidence = {
    schemaVersion: 1,
    benchmark: 'deqr-phase00-baseline-audit',
    label: options.label,
    generatedAt: new Date().toISOString(),
    environment: {
      node: process.version,
      platform: platform(),
      release: release(),
      arch: arch(),
      totalMemoryBytes: totalmem(),
      gcAvailable: typeof global.gc === 'function',
      ...gitMetadata(),
    },
    shippingConstants: {
      v1FountainBlockSizeBytes: V1_FOUNTAIN_BLOCK_SIZE_BYTES,
      v1MaxBlockCount: V1_MAX_BLOCK_COUNT,
      v1MaxSerializedContainerBytes: V1_MAX_SERIALIZED_CONTAINER_BYTES,
      v1MaxSerializedContainerMib: V1_MAX_SERIALIZED_CONTAINER_BYTES / MIB,
      containerMaxFileSizeBytes: MAX_FILE_SIZE,
      shippingTransferFps: SHIPPING_TRANSFER_FPS,
      opticalPayloadBytesPerSecond: SHIPPING_TRANSFER_FPS * V1_FOUNTAIN_BLOCK_SIZE_BYTES,
    },
    configuration: {
      mode: options.mode,
      sizesMib: options.sizesMib,
      samples: options.samples,
      decodeMaxMib: options.decodeMaxMib,
      extensionSizeMib: options.extensionSizeMib,
      corpora: ['text (redundant, gzip-friendly)', 'random (LCG, high entropy)'],
      source: 'deterministic synthetic bytes generated by this script; no payload bytes are recorded',
      delivery: 'in-process desktop encoder into the browser-safe ReceiverSession; no camera, no display, no network',
    },
    boundary,
    capacity,
    extensionMatrix,
    extensionSummary,
    blockedExtensionProbe: blockedProbe,
  };

  await writeFile(output, `${JSON.stringify(evidence, null, 2)}\n`, 'utf8');
  console.log(
    `PHASE00_BASELINE_COMPLETE capacity=${capacity.length}`
    + ` extensionSamples=${extensionMatrix.length} output=${relative(process.cwd(), output)}`,
  );
}

void main().catch((error: unknown) => {
  console.error(`PHASE00_BASELINE_FAILED ${errorMessage(error)}`);
  process.exitCode = 1;
});
